/*The fun and easy project “Guess the Number” is a short Java project that allows the user to guess the number 
generated by the computer & involves the following steps:

The system generates a random number from a given range, say 1 to 100.
The user is prompted to enter their given number in a displayed dialogue box.
The computer then tells if the entered number matches the guesses number or it is higher/lower than the generated number.
The game continues under the user guessing the number.
You can also incorporate further details as:

Limiting the number of attempts.
Adding more rounds.
Displaying score.
Giving points based on the number of attempts.*/


package Task2;

import java.util.Random;
import java.util.Scanner;

public class Number_guessing 
{
	public static void main(String[] args) 
	{
		int min=1,max=100,attempt=1, rounds=1,score=0,r=1,a=1;
		boolean flag=false;
		String ch = "Yes";
		Scanner sc=new Scanner(System.in);
		Random rd = new  Random();
		int n=rd.nextInt(max - min + 1) + min;
		System.out.println("Number generated is "+ n);
		while(attempt<=3 && ch.equals("Yes") && flag==false)
		{
			
			System.out.println("\nAttempt "+ attempt);
			
			while(rounds<=7)
			{
				System.out.println("\nRound " + rounds);
				System.out.println("Hey user!! guess a number between 1 and 100");
				int m=sc.nextInt();
				if(m==n && rounds<=7)
				{
					switch(rounds)
					{
					case 1:
						System.out.println("Congratulations you guessed the number at first round..You score is 100");
						score=100;
						flag=true;
						break;
					case 2:
						System.out.println("Congratulations you guessed the number at second round...You score is 90");
						score=90;
						flag=true;
						break;
					case 3:
						System.out.println("Congratulations you guessed the number at third round...You score is 80");
						score=80;
						flag=true;
						break;
					case 4:
						System.out.println("Congratulations you guessed the number at fourth round...You score is 70");
						score=70;
						flag=true;
						break;
					case 5:
						System.out.println("Congratulations you guessed the number at fifth round...You score is 60");
						score=60;
						flag=true;
						break;
					case 6:
						System.out.println("Congratulations you guessed the number at sixth round...You score is 50");
						score=50;
						flag=true;
						break;
					case 7:
						System.out.println("Congratulations you guessed the number at seventh round...You score is 40");
						score=40;
						flag=true;
						break;
					default:
						System.out.println("Sorry you exceeded number of attempts");
						flag=true;
						break;
						
				}
					break;
				}
			else if(m>n && rounds<=7)
			{
				System.out.println("Your entered number is higher than the generated number");
				rounds++;
			}
			else if(m<n && rounds<=7)
			{
				System.out.println("Your entered number is lower than the generated number");
				rounds++;
			}
			}
			r=rounds;
			a=attempt;
			if(flag == true)
			{
				break;
			}
			else
			{
				System.out.println("\nYou reached 7 rounds");
				System.out.println("\nWould you like to play again? Yes Or No");
				ch=sc.next();
				attempt++;
				rounds=1;
			}
		}
				System.out.println("\nGAME OVER");
				System.out.println("Total number of attempts= "+ a);
				System.out.println("Total number of rounds= "+ r);
				System.out.println("Your score is "+score);
			
		}
		}
